<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x86;ARM64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="fNbt" Version="1.0.0" />
    <PackageReference Include="System.Management" Version="10.0.5" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
  </ItemGroup>
</Project>
